version: '3.0'

expectations:
  population_size: 1000

actions:

# EXTRACT DATA FOR EXPOSED AND POTENTIAL CONTROLS 

  ## Extract data on vaccinated people 
  ## NB; This study definition only contains the data needed for matching
  generate_exposed_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_exposed
    outputs:
      highly_sensitive:
        cohort: output/input_exposed.csv

  ## Extract data on potential concurrent controls 
  generate_concurrent_controls:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_concurrent_controls
    outputs:
      highly_sensitive:
        cohort: output/input_concurrent_controls.csv

  ## Extract data on potential historical controls

# MATCH EXPOSED TO CONTROLS 
# Note that exposed and resulting matches need to_c be extracted into separate csvs to allow appropriate covariate information to be extracted 

  ## Match vaccinated people to concurrent controls 
  match_concurrent:
    run: python:latest python analysis/matching.py
    needs: [generate_exposed_cohort, generate_concurrent_controls]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_concurrent.txt
      highly_sensitive:
        matched_cases: output/matched_cases_concurrent.csv
        matched_matches: output/matched_matches_concurrent.csv
        matched_all: output/matched_combined_concurrent.csv

  ## Match vaccinated people to historical controls 

  ## Extract time-dependent data for matched concurrent controls 
  add_covariates_concurrent_controls:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_complete_concurrent 
    needs: [match_concurrent]
    outputs:
      highly_sensitive:
        cohort: output/input_complete_concurrent.csv

  ## Extract time-dependent data for matched historical controls 

# CREATE THE REQUIRED POPULATIONS 
## ie, merge case and match data, apply remaining inclusions and exclusions

  apply_exclusion_criteria:
    run: stata-mp:latest analysis/01_apply_exclusion_criteria.do 
    needs: [add_covariates_concurrent_controls, match_concurrent] 
    outputs:
      moderately_sensitive: 
        log: output/logs/01_apply_exclusion_criteria.log
      highly_sensitive:
        interim_data: output/concurrent_cohort.dta



