version: '3.0'

expectations:
  population_size: 10000

actions:

  ## Extract cohort 
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_cohort
    outputs:
      highly_sensitive:
        cohort: output/input_cohort.csv


